version: '3.4'

services:
  web:
    build: .
    env_file: .env
    depends_on:
      - db
  db:
    image: 'postgres:11'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE: api
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
volumes:
  pgdata: null
