"""empty message

Revision ID: 10e259fdba0c
Revises: e472227c75d8
Create Date: 2021-01-07 19:26:08.354470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10e259fdba0c'
down_revision = 'e472227c75d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pf_operations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['tickers.code'], ),
    sa.ForeignKeyConstraint(['token'], ['tokens.token'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'tokens', ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='unique')
    op.drop_table('pf_operations')
    # ### end Alembic commands ###
