"""empty message

Revision ID: 6d9ddf2403cf
Revises: 10e259fdba0c
Create Date: 2021-01-07 19:31:27.666712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9ddf2403cf'
down_revision = '10e259fdba0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pf_operations', sa.Column('performed_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'pf_operations', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pf_operations', type_='unique')
    op.drop_column('pf_operations', 'performed_at')
    # ### end Alembic commands ###
