"""empty message

Revision ID: 975bf41b6724
Revises: 6d9ddf2403cf
Create Date: 2021-01-08 15:51:26.385481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975bf41b6724'
down_revision = '6d9ddf2403cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickers', sa.Column('log', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickers', 'log')
    # ### end Alembic commands ###
