"""empty message

Revision ID: bc18c9723776
Revises: 975bf41b6724
Create Date: 2021-01-08 16:29:28.987393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc18c9723776'
down_revision = '975bf41b6724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickers', sa.Column('lot', sa.Integer(), nullable=True))
    op.drop_column('tickers', 'log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickers', sa.Column('log', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tickers', 'lot')
    # ### end Alembic commands ###
