"""empty message

Revision ID: e472227c75d8
Revises: e364b89655b2
Create Date: 2021-01-07 18:49:26.628314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e472227c75d8'
down_revision = 'e364b89655b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('token', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('token'),
    sa.UniqueConstraint('token')
    )
    op.create_unique_constraint(None, 'quotes', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotes', type_='unique')
    op.drop_table('tokens')
    # ### end Alembic commands ###
